### ISSUE TITLE
how do we close an issue ?

### ISSUE THREAD

**Issue by jdcourcol** [HumanBrainProject/hbp-issuetracker#2]
I did not find anything obvious for this

**Comment by apdavison** [comment]
1. Click on the edit (cog) button
2. Select the checkbox(es) for the ticket(s) you want to close
3. In the "Action" menu choose "Close"
4. Click "Apply"

**Comment by jdcourcol** [comment]
Thank you Andrew.
![image](https://cloud.githubusercontent.com/assets/5441880/26572150/292f83a0-4519-11e7-9e31-6cddf1626273.png)

However, I don't see a checkbox for the ticket ( I attached what I see)

**Comment by apdavison** [comment]
Sorry, you have to do this in the ticket list view, not in the view for individual tickets.

This is clearly not a very intuitive ui.

**Comment by jdcourcol** [comment]
I see it now. Thank you.
